dist: bionic
sudo: required
language: c
compiler:
  - gcc
branches:
  only:
    - master
    - dev
before_install:
  - pwd
  - git clone -b $TRAVIS_BRANCH --recurse-submodules -j8 https://github.com/gonapps-org/libgenc
  - cd libgenc
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../
  - pwd
  - git clone -b $TRAVIS_BRANCH --recurse-submodules https://github.com/gonapps-org/libgaio
  - cd libgaio
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../
  - pwd
  - git clone -b $TRAVIS_BRANCH --recurse-submodules https://github.com/gonapps-org/libfastdl
  - cd libfastdl
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../
  - pwd
  - git clone -b $TRAVIS_BRANCH https://github.com/vinbero/vinbero-ifaces
  - cd vinbero-ifaces
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../
  - pwd
  - git clone -b $TRAVIS_BRANCH --recurse-submodules https://github.com/vinbero/libvinbero_com
  - cd libvinbero_com
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

install:
  - sudo apt-get install -y libcmocka-dev libjansson-dev liblua5.3-dev libboost-dev libboost-program-options-dev nlohmann-json-dev flex libfl-dev g++ make cmake

  - pwd
  - cd libgenc/build
  - make
  - sudo make install
  - cd ../../
  - pwd
  - cd libgaio/build
  - make
  - sudo make install
  - cd ../../
  - pwd
  - cd libfastdl/build
  - make
  - sudo make install
  - cd ../../
  - pwd
  - cd vinbero-ifaces/build
  - make
  - sudo make install
  - cd ../../
  - pwd
  - cd libvinbero_com/build
  - make
  - sudo make install
  - cd ../../

before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_WITH_COVERAGE=ON ..
script: make && ctest -V
after_success:
  - bash <(curl -s https://codecov.io/bash)

